"""Normalized schools and classes derived from the free-text extracted data.

taxonomy.json (generated by scripts/import_taxonomy.py from the reviewed
workbook) maps the ~200 raw class spellings and ~100 raw school spellings onto
canonical names. The derived tables are rebuilt on every start, so shipping an
updated taxonomy.json takes effect without touching the user's edits.
"""
from __future__ import annotations

import json
import re
import sqlite3
from functools import lru_cache
from typing import Any

from spellbook.config import PACKAGE_ROOT


UNCLASSIFIED = "unclassified"

SCHEMA = """
CREATE TABLE IF NOT EXISTS class_catalog(
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    kind TEXT NOT NULL CHECK(kind IN ('class','domain','other')),
    name_en TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS spell_class_levels(
    spell_entry_id TEXT NOT NULL REFERENCES spell_entries(id) ON DELETE CASCADE,
    class_id INTEGER NOT NULL REFERENCES class_catalog(id) ON DELETE CASCADE,
    level INTEGER NOT NULL CHECK(level BETWEEN 0 AND 9),
    note TEXT NOT NULL DEFAULT '',
    PRIMARY KEY(spell_entry_id, class_id, level)
);
CREATE INDEX IF NOT EXISTS idx_spell_class_levels_class ON spell_class_levels(class_id, level);
CREATE TABLE IF NOT EXISTS spell_schools(
    spell_entry_id TEXT NOT NULL REFERENCES spell_entries(id) ON DELETE CASCADE,
    school TEXT NOT NULL,
    PRIMARY KEY(spell_entry_id, school)
);
CREATE INDEX IF NOT EXISTS idx_spell_schools_school ON spell_schools(school);
"""


@lru_cache(maxsize=1)
def data() -> dict[str, Any]:
    return json.loads((PACKAGE_ROOT / "taxonomy.json").read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def _school_patterns() -> list[tuple[str, re.Pattern[str]]]:
    return [(school["key"], re.compile(school["pattern"])) for school in data()["schools"]]


def schools() -> list[dict[str, str]]:
    return [{"key": s["key"], "name": s["name"]} for s in data()["schools"]] + [{"key": UNCLASSIFIED, "name": "未分類"}]


def school_keys(entry_id: str, text: str | None) -> list[str]:
    """Canonical schools for a school text. Reviewed overrides apply only while
    the text is still the one that was reviewed; edited text uses the rules."""
    text = text or ""
    override = data()["school_overrides"].get(entry_id)
    if override is not None and override["text"] == text:
        keys = override["schools"]
    else:
        keys = [key for key, pattern in _school_patterns() if pattern.search(text)]
    return keys or [UNCLASSIFIED]


def set_schools(connection: sqlite3.Connection, entry_id: str, text: str | None) -> None:
    connection.execute("DELETE FROM spell_schools WHERE spell_entry_id=?", (entry_id,))
    connection.executemany(
        "INSERT INTO spell_schools(spell_entry_id,school) VALUES(?,?)",
        [(entry_id, key) for key in school_keys(entry_id, text)],
    )


def refresh(connection: sqlite3.Connection) -> None:
    connection.executescript(SCHEMA)
    taxonomy = data()
    connection.execute("DELETE FROM spell_class_levels")
    connection.execute("DELETE FROM spell_schools")
    connection.execute("DELETE FROM class_catalog")
    connection.executemany(
        "INSERT INTO class_catalog(id,name,kind,name_en,sort_order) VALUES(?,?,?,?,?)",
        [(index + 1, c["name"], c["kind"], c["name_en"], index) for index, c in enumerate(taxonomy["classes"])],
    )
    class_ids = {c["name"]: index + 1 for index, c in enumerate(taxonomy["classes"])}
    aliases, fixes = taxonomy["class_aliases"], taxonomy["level_fixes"]

    rows = set()
    for entry_id, raw_name, level, note in connection.execute(
        "SELECT l.spell_entry_id,c.name,l.spell_level,l.note FROM spell_levels l JOIN classes c ON c.id=l.class_id"
    ):
        if entry_id in fixes:
            continue
        for name in aliases.get(raw_name, ()):
            rows.add((entry_id, class_ids[name], level, note or ""))
    existing = {row[0] for row in connection.execute("SELECT id FROM spell_entries")}
    for entry_id, levels in fixes.items():
        if entry_id in existing:
            rows.update((entry_id, class_ids[name], level, "") for name, level in levels)
    # A raw row can map onto a class+level another row already produced; keep one.
    unique = {(entry, cls, level): note for entry, cls, level, note in sorted(rows)}
    connection.executemany(
        "INSERT INTO spell_class_levels(spell_entry_id,class_id,level,note) VALUES(?,?,?,?)",
        [(entry, cls, level, note) for (entry, cls, level), note in unique.items()],
    )
    connection.executemany(
        "INSERT INTO spell_schools(spell_entry_id,school) VALUES(?,?)",
        [
            (entry_id, key)
            for entry_id, text in connection.execute("SELECT id,school FROM spell_entries").fetchall()
            for key in school_keys(entry_id, text)
        ],
    )
